### ISSUE TITLE
CAN you ADD support for 1.21.4 

### ISSUE THREAD

**Issue by Darkmager** [Paulem79/BetterThanMending-Spigot#2]
It does not work on 1.21.4 server

[08:52:54] [Server thread/ERROR]: Error occurred while enabling BetterMending v2.6.4.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.Enum org.bukkit.Sound.valueOf(java.lang.Class, java.lang.String)'
	at BetterThanMending-2.6.4.3.jar/ovh.paulem.btm.listeners.MendingUseListener.<clinit>(MendingUseListener.java:28) ~[BetterThanMending-2.6.4.3.jar:?]
	at BetterThanMending-2.6.4.3.jar/ovh.paulem.btm.BetterMending.onEnable(BetterMending.java:48) ~[BetterThanMending-2.6.4.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:369) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.4.jar:1.21.4-2376-4bf1b98]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Paulem79** [comment]
Fixed on the latest release, thanks for your report ! :D

**Comment by Paulem79** [comment]
And it also fixed an error with old versions of Minecraft, I saw it just now :D
